-------------------------
-- Simplified Chinese Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- Translation by chillzz
-- miui.en
-- 20150202
-------------------------
localization_Chinese_table = {
    calories_table={
		{str="≈ Gurke (100g)",	calories=14},
		{str="≈ Hühnerbrühe (100g)",	calories=15},
		{str="≈ Kohl (100g)",	calories=16},
		{str="≈ Eingelegte Tomaten (100g)",	calories=19},
		{str="≈ Pilze (100g)",	calories=20},
		{str="≈ Radieschen (100g)",	calories=21},
		{str="≈ Aubergine (100g)",	calories=24},
		{str="≈ Kürbis (100g)",	calories=25},
		{str="≈ Sauerkraut (100g)",	calories=25},
		{str="≈ Pilzsuppe (100g)",	calories=26},
		{str="≈ Brokkoli (100g)",	calories=27},
		{str="≈ Gemüsesuppe (100g)",	calories=28},
		{str="≈ Erdbeeren (100g)",	calories=30},
		{str="≈ Borschtsch (100g)",	calories=36},
		{str="≈ Miso-Suppe (100g)",	calories=36},
		{str="≈ Rote Bete (100g)",	calories=36},
		{str="≈ Apfel (100g)",	calories=37},
		{str="≈ Orange (100g)",	calories=38},
		{str="≈ Kartoffelsuppe (100g)",	calories=39},
		{str="≈ Wassermelone (100g)",	calories=39},
		{str="≈ Sauerampfersuppe (100g)",	calories=40},
		{str="≈ Buttermilch 1% (100g)",	calories=40},
		{str="≈ Coca-Cola (100g)",	calories=42},
		{str="≈ 1.5% Milch (100g)",	calories=45},
		{str="≈ Red Bull (100g)",	calories=45},
		{str="≈ Fischsuppe (100g)",	calories=46},
		{str="≈ Pfirsich (100g)",	calories=46},
		{str="≈ Hochlandkäse (25g)",	calories=48},
		{str="≈ Kirsche (100g)",	calories=52},
		{str="≈ Orangensaft (100g)",	calories=54},
		{str="≈ 3.2% Milch (100g)",	calories=58},
		{str="≈ Ratatouille (100g)",	calories=60},
		{str="≈ Kartoffelpüree (100g)",	calories=65},
		{str="≈ Erbsensuppe (100g)",	calories=66},
		{str="≈ Mango (100g)",	calories=67},
		{str="≈ Linsensuppe (100g)",	calories=68},
		{str="≈ Erdbeergelee (100g)",	calories=69},
		{str="≈ Joghurt 1.5% (100g)",	calories=70},
		{str="≈ Krabbensticks (100g)",	calories=73},
		{str="≈ Tintenfisch (100g)",	calories=75},
		{str="≈ Champagner (100g)",	calories=76},
		{str="≈ Wein 13% (100g)",	calories=78},
		{str="≈ Krautgulasch (100g)",	calories=81},
		{str="≈ Salzkartoffeln (100g)",	calories=82},
		{str="≈ Absinth 60% ​​(100g)",	calories=83},
		{str="≈ Kartoffelpüree mit Milch (100g)",	calories=85},
		{str="≈ Gekochtes Ei (55g)",	calories=88},
		{str="≈ Banane (100g)",	calories=89},
		{str="≈ Tomaten-Bohnen (100g)",	calories=92},
		{str="≈ Ketchup (100g)",	calories=93},
		{str="≈ Reis mit Gemüse (100g)",	calories=94},
		{str="≈ Korntoast (1 Scheibe)",	calories=95},
		{str="≈ Thunfisch (100g)",	calories=96},
		{str="≈ Gekochter Zander (100g)",	calories=97},
		{str="≈ Gemüseeintopf (100g)",	calories=99},
		{str="≈ Gekochter Karpfen (100g)",	calories=102},
		{str="≈ Obstsalat (100g)",	calories=103},
		{str="≈ Putenfilet (100g)",	calories=104},
		{str="≈ Schweinefleisch (100g)",	calories=105},
		{str="≈ Reis (100g)",	calories=113},
		{str="≈ Zeppelins (100g)",	calories=117},
		{str="≈ Rührei",	calories=119},
		{str="≈ Melonenkürbispüree (100g)",	calories=122},
		{str="≈ Japanische Mayonnaise (100g)",	calories=134},
		{str="≈ Marshmallow (1 Stk.)",	calories=135},
		{str="≈ Hüttenkäse (100g)",	calories=136},
		{str="≈ Avocadoröllchen",	calories=140},
		{str="≈ Cappuccino (100g)",	calories=140},
		{str="≈ Lobio (100g)",	calories=141},
		{str="≈ Rinderzunge (100g)",	calories=146},
		{str="≈ Rindergulasch (100g)",	calories=148},
		{str="≈ Gekochtes Hühnerfilet (100g)",	calories=153},
		{str="≈ Bratkartoffeln (100g)",	calories=154},
		{str="≈ Pizza Margherita (100g)",	calories=157},
		{str="≈ Fleischbällchen (100g)",	calories=159},
		{str="≈ Buchweizen (100g)",	calories=160},
		{str="≈ Roggenbrot (100g)",	calories=165},
		{str="≈ Truthahnbraten (100g)",	calories=165},
		{str="≈ Geräuchertes Hähnchen (100g)",	calories=184},
		{str="≈ Schweinefleisch (100g)",	calories=195},
		{str="≈ Salami (100g)",	calories=198},
		{str="≈ Lachs (201g)",	calories=201},
		{str="≈ Sauerrahm 20% (100g)",	calories=204},
		{str="≈ Sahne (100g)",	calories=206},
		{str="≈ Pasta Bolognese (100g)",	calories=208},
		{str="≈ Schwarzbrot (100g)",	calories=214},
		{str="≈ Kandierte Früchte (100g)",	calories=216},
		{str="≈ Salzhering (100g)",	calories=217},
		{str="≈ Champignons (100g)",	calories=219},
		{str="≈ Cäsar-Salat (100g)",	calories=221},
		{str="≈ Omelette (100g)",	calories=222},
		{str="≈ Leichtbier (0.5l)",	calories=225},
		{str="≈ Haferbrot (100g)",	calories=226},
		{str="≈ Lammeintopf (100g)",	calories=226},
		{str="≈ Eisbecher (100g)",	calories=227},
		{str="≈ McD Hamburger",	calories=229},
		{str="≈ Schweinebraten (100g)",	calories=233},
		{str="≈ Weißbrot (100g)",	calories=235},
		{str="≈ Pitabrot (100g)",	calories=236},
		{str="≈ Wodka 40% (100g)",	calories=237},
		{str="≈ Basturma (100g)",	calories=240},
		{str="≈ Hamon (100g)",	calories=241},
		{str="≈ Ravioli (100g)",	calories=245},
		{str="≈ Roter Kaviar (100g)",	calories=249},
		{str="≈ Shawarma (100g)",	calories=250},
		{str="≈ Hühnerwurst (100g)",	calories=259},
		{str="≈ Frikadellen (100g)",	calories=260},
		{str="≈ Rosinen (100g)",	calories=262},
		{str="≈ McD Cheeseburger",	calories=264},
		{str="≈ Milchwürstchen (100g)",	calories=270},
		{str="≈ Schinken (100g)",	calories=270},
		{str="≈ Geräucherter Kabeljau (100g)",	calories=270},
		{str="≈ McD McNuggets (100g)",	calories=272},
		{str="≈ Knödel (100g)",	calories=275},
		{str="≈ Gegrillter Lachs (100g)",	calories=283},
		{str="≈ Schwarzer Kaviar (100g)",	calories=289},
		{str="≈ Mayonnaise (100g)",	calories=299},
		{str="≈ Honig (100g)",	calories=302},
		{str="≈ McD Pommes (100 g)",	calories=303},
		{str="≈ Dates (100g)",	calories=306},
		{str="≈ Apfelpfannkuchen (100g)",	calories=306},
		{str="≈ Kohlroulade (100g)",	calories=311},
		{str="≈ Pfannkuchen (100g)",	calories=322},
		{str="≈ Omelett mit Käse (100g)",	calories=324},
		{str="≈ Leberwurst (100g)",	calories=326},
		{str="≈ Donuts (100g)",	calories=329},
		{str="≈ Käsekuchen (100g)",	calories=331},
		{str="≈ Pfannkuchen mit Butter (100g)",	calories=332},
		{str="≈ Döner (100g)",	calories=339},
		{str="≈ Spaghetti (100g)",	calories=344},
		{str="≈ Muffin (100g)",	calories=345},
		{str="≈ Lebkuchen (100g)",	calories=350},
		{str="≈ Bœuf Stroganoff (100g)",	calories=355},
		{str="≈ Cornflakes (100g)",	calories=363},
		{str="≈ Pasta (100g)",	calories=371},
		{str="≈ Steak (100g)",	calories=384},
		{str="≈ Crackers (100g)",	calories=386},
		{str="≈ Zucker (100g)",	calories=398},
		{str="≈ Haferkekse (100g)",	calories=440},
		{str="≈ Schnitzel (100g)",	calories=456},
		{str="≈ Lasagne (100g)",	calories=460},
		{str="≈ Gänsestopfleber (100g)",	calories=462},
		{str="≈ Honigkuchen (100g)",	calories=478},
		{str="≈ Popcorn (100g)",	calories=480},
		{str="≈ Twix",	calories=483},
		{str="≈ Snickers",	calories=497},
		{str="≈ Speck (100g)",	calories=500},
		{str="≈ McD Big Mac",	calories=510},
		{str="≈ Lays Chips (100g)",	calories=510},
		{str="≈ KitKat",	calories=524},
		{str="≈ Tiramisu (100g)",	calories=540},
		{str="≈ Pringles (100g)",	calories=540},
		{str="≈ Schokolade (100g)",	calories=546},
		{str="≈ Napoleon Kuchen (100g)",	calories=552},
		{str="≈ Salami (100g)",	calories=568},
		{str="≈ Gänsebraten (100g)",	calories=620},
		{str="≈ Bratknödel (100g)",	calories=764},
		{str="≈ McD Big Tasty",	calories=850},
    },

    ok='OK',

    hour='Std.',
    minute='Min.',
    month='Monat',
    day='Tag',
    step="Schritte",
    km='km',
    mile='Meilen',
    minute_format='%d Min.',
    hour_minute_format='%d Std. %d Min.',
    hour_format='%d Std.',

    welcome_use="Willkommen",
    last_week_walked_format='Letzte Woche sind Sie %d Schritte gegangen',
    last_week_walked_info_format='%d km gelaufen, %d cal verbrannt',
    last_month_walked_format='Letzten Monat sind Sie %d Schritte gegangen',
    last_month_walked_info_format='%d km gelaufen, %d cal verbrannt',

    get_over_format=", über %dg Fett",
    click_to_get_help="Mehr über das MiBand erfahren",
    take_a_walk="Machen Sie einen Spaziergang mit dem MiBand",
    take_a_walk_info="Ihr MiBand zeichnet jeden Ihrer Schritte auf",
    unlock_hint="Sesam öffne dich!",
    unlock_hint_info="Nutzen Sie Ihr MiBand, um Ihr Gerät automatisch zu entsperren.",
    unlock_password_hint="Richten Sie eine Bildschirmsperre ein, um Ihr Telefon zu sichern.",
    unlock_password_hint_info="Das MiBand bietet die beste Bildschirmentsperrung.",
    no_data_hint_0="Die US National Sleep Foundation empfiehlt jeden Tag 7-9 Stunden Schlaf",
    no_data_hint_1="Wiederholungen sind der Anfang des Erfolges",
    no_data_hint_2="Streben Sie für den Fortschritt, nicht nach der Perfektion",
    no_data_hint_3="Ganz egal wie langsam Sie sind, sie überrunden jeden, der auf der Couch sitzt",
    not_binded_hint="Es ist kein MiBand mit diesem Konto verbunden",
    not_binded_hint_info="Sie können dies ebenfalls in den Einstellungen einrichten",
    new_record_info="Sie haben einen Rekord aufgestelllt",
    new_record_format="%d Schritte, %s %d",
    today_goal_reached="Sie haben Ihr heutiges Ziel erreicht!",
    today_goal_reached_click_info="Tippen, um die Ergebnisse anzuzeigen.",
    week_continue_reach_goal="Sie",

    challenge_format="Sie haben Ihr Ziel seit %d Tagen in Folge erreicht",
    personal_best_format="Ihre längste Serie ist %d Tage",
    continue_with_skips_title="Sie haben Ihr Ziel gestern nicht erreicht. Sagen wir es war ein fauler Tag ;)",
    continue_with_skips_title_today="Sie haben Ihr heutiges Ziel nicht erreicht. Sagen wir es war ein fauler Tag ;)",
    personal_best_with_skips_format="Sie haben noch %d faule Tage übrig ;)",
    continue_used_n_skips_format="Sie haben Ihr Ziel seit %d Tagen in Folge erreicht! Sie haben noch %d faule Tage",
    continue_used_0_skips_format="Sie haben Ihr Ziel seit %d Tagen in Folge erreicht! Sie haben keine faulen Tage mehr übrig",
    personal_best_on_skip_day_title="%d Tage in Folge! Sie haben sich einen faulen Tag verdient",
    personal_best_on_skip_day_info="Wenn Sie Ihr Ziel 7 Tage lang erfüllen, bekommen Sie einen faulen Tag. Sie können diese nutzen, um Tage zu kompensieren, wo Sie das Ziel nicht erreicht haben",
    manual_lazy_title="Sie haben Ihr heutiges Ziel nicht erreicht",
    manual_lazy_subtitle="Ihre Serie wird fortgesetzt, wenn Sie den heutigen Tag als faulen Tag markieren",
    manual_lazy_title_used="Heute ist ein fauler Tag",
    manual_lazy_subtitle_used="Sie können sich weitere faule Tage verdienen, indem Sie Rekorde brechen",
    manual_fail_ytd_title = "Sie haben Ihre Serie gestern beendet",
    manual_fail_ytd_subtitle = "Serie war %d lang",

    active_time_format_0="%d Min.",
    active_time_format_1="%d Std.",
    active_time_format_2="%d Std. %d Min.",
    activie_run_format_0="Gelaufen %s. Gut gemacht!",
    activie_run_format_1="Gelaufen %s. Sie machen das fantastisch!",
    activie_run_format_2="Gelaufen %s.",
    activie_run_consumed="%d cal verbrannt %s",

    get_distance_format="ungefähr %dm",
    get_distance_format_british="%d Zoll",
    activity_walk_format="%s %d Schritte gegangen, %s",
    activity_walk_consumed_format="%d cal verbrannt %s",
    activity_rope_skipping_format="%s %d mal Seilgesprungen",
    activity_situp_format="%s %d Sit-Ups gemacht",
    activity_consumed_format="%d cal verbrannt %s",
    activity_activity_format="%s %s aktiv, %s",
    activity_activity_format_run="%s Aktiv für %s, %s gelaufen",
    last_night_sleeped_good_format="Letzte Nacht haben Sie %s geschlafen",
    last_night_sleeped_normal_format="Letzte Nacht haben Sie %s geschlafen",
    deep_sleep_format="Tiefschlafphase war %s",

    battery_low_info="Laden Sie Ihr MiBand auf",
    battery_very_low_info="Der Akkustand Ihres MiBands neigt sich dem Ende",

    cannot_find_bracelet="MiBand kann nicht gefunden werden.",
    cannot_find_bracelet_info="Stellen Sie sicher, dass Ihr MiBand aufgeladen ist",

    bracelet_disconnect = "Sie können das MiBand nicht verbinden? Drücken, um Hilfe zu bekommen.",

    challenge_to_get="%s Tage von einem neuem Rekord entfernt!",
    record_reach_max="Sie haben Ihren Rekord gebrochen!",
    new_record_born="Neuen Rekord aufgestellt!",

    ---====== Weather tips ===============
    weather_tips_title_0 = "Starke Verschmutzung, versuchen Sie drinnen zu bleiben",
    weather_tips_title_1 = "Starke Verschmutzung, versuchen Sie drinnen zu bleiben",
    weather_tips_info = "Sit-Ups oder Seilspringen sind großartige Indoor-Sportarten!",

    ---------------Weight scale -------------------
    welcome_use_weight_scale = "Waage erfolgreich verbunden",
    welcome_use_weight_scale_not_bind = "Drücken, um Waage zu verbinden",
    welcome_use_mi_health="Willkommen bei MiSports",

    select_devices="Geräte zum Verbinden auswählen",
    daily_steps_not_comlete = "Sie benötigen noch %s Schritte!",
}
